# KB Card 파일 불러오기

## 0. 초기 세팅
각종 라이브러리를 불러오고 초기값 등을 세팅합니다.

In [30]:
#!uv add xlrd

In [31]:
from pathlib import Path
import pandas as pd

In [32]:
PROJECT_ROOT = Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data" / "raw"
KB_CARD_XLS = DATA_DIR / "kbcard.xls"

## 1. 데이터 파일 조회 및 전처리

In [33]:
df = pd.read_excel(KB_CARD_XLS, header=6)

# 헤더 줄바꿈 지우기. 국민은행은 헤더에 보기좋으락 줄바꿈을 해둠
df.columns = df.columns.str.replace("\n", "", regex=False)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   이용일         7 non-null      object
 1   이용시간        7 non-null      object
 2   이용고객명       7 non-null      object
 3   이용카드명       7 non-null      object
 4   이용하신곳       7 non-null      object
 5   국내이용금액(원)   7 non-null      int64
 6   해외이용금액($)   7 non-null      int64
 7   결제방법        7 non-null      object
 8   가맹점정보       0 non-null      float64
 9   할인금액        7 non-null      int64
 10  적립(예상)포인트리  7 non-null      int64
 11  상태          7 non-null      object
 12  결제예정일       2 non-null      object
 13  승인번호        7 non-null      int64
dtypes: float64(1), int64(5), object(8)
memory usage: 916.0+ bytes

In [35]:
df.head()

,이용일,이용시간,이용고객명,이용카드명,이용하신곳,국내이용금액(원),해외이용금액($),결제방법,가맹점정보,할인금액,적립(예상)포인트리,상태,결제예정일,승인번호
0,2026-01-03,16:28,주진영,KB국민 탄탄대로 올쇼핑카드,쿠팡(쿠페이),32600,0,일시불,NaN,0,0,전표미매입,NaN,30118172
1,2026-01-03,16:13,주진영,KB국민 탄탄대로 올쇼핑카드,네이버페이,24840,0,일시불,NaN,0,0,전표미매입,NaN,30118161
2,2026-01-03,16:00,주진영,KB국민 탄탄대로 올쇼핑카드,네이버페이,47500,0,일시불,NaN,0,0,전표미매입,NaN,30118150
3,2026-01-03,15:38,임준열,KB국민 탄탄대로 올쇼핑카드,(주)딜리유통,42000,0,일시불,NaN,0,0,전표매입,2026-02-14,30118141
4,2026-01-03,10:04,임준열,KB국민 탄탄대로 올쇼핑카드,웨이브(푹TV)자동,10900,0,일시불,NaN,0,0,전표미매입,NaN,30118138

In [36]:
# 날짜 컬럼을 datetime 타입으로 변환
df["이용일"] = pd.to_datetime(df["이용일"], errors="coerce")
df["결제예정일"] = pd.to_datetime(df["결제예정일"], errors="coerce")
df["이용시간"] = df["이용시간"].astype("string")

In [37]:
# 텍스트 컬럼들을 string 타입으로 변환
text_cols = [
    "이용고객명",
    "이용카드명",
    "이용하신곳",
    "결제방법",
    "상태",
    "가맹점정보",
]

for col in text_cols:
    df[col] = df[col].astype("string")

In [38]:
amount_cols = [
    "국내이용금액(원)",
    "해외이용금액($)",
    "할인금액",
    "적립(예상)포인트리",
]
df[amount_cols] = df[amount_cols].fillna(0).astype("int64")

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   이용일         7 non-null      datetime64[ns]
 1   이용시간        7 non-null      string
 2   이용고객명       7 non-null      string
 3   이용카드명       7 non-null      string
 4   이용하신곳       7 non-null      string
 5   국내이용금액(원)   7 non-null      int64
 6   해외이용금액($)   7 non-null      int64
 7   결제방법        7 non-null      string
 8   가맹점정보       0 non-null      string
 9   할인금액        7 non-null      int64
 10  적립(예상)포인트리  7 non-null      int64
 11  상태          7 non-null      string
 12  결제예정일       2 non-null      datetime64[ns]
 13  승인번호        7 non-null      int64
dtypes: datetime64[ns](2), int64(5), string(7)
memory usage: 916.0 bytes

In [40]:
df.head()

,이용일,이용시간,이용고객명,이용카드명,이용하신곳,국내이용금액(원),해외이용금액($),결제방법,가맹점정보,할인금액,적립(예상)포인트리,상태,결제예정일,승인번호
0,2026-01-03,16:28,주진영,KB국민 탄탄대로 올쇼핑카드,쿠팡(쿠페이),32600,0,일시불,<NA>,0,0,전표미매입,NaT,30118172
1,2026-01-03,16:13,주진영,KB국민 탄탄대로 올쇼핑카드,네이버페이,24840,0,일시불,<NA>,0,0,전표미매입,NaT,30118161
2,2026-01-03,16:00,주진영,KB국민 탄탄대로 올쇼핑카드,네이버페이,47500,0,일시불,<NA>,0,0,전표미매입,NaT,30118150
3,2026-01-03,15:38,임준열,KB국민 탄탄대로 올쇼핑카드,(주)딜리유통,42000,0,일시불,<NA>,0,0,전표매입,2026-02-14,30118141
4,2026-01-03,10:04,임준열,KB국민 탄탄대로 올쇼핑카드,웨이브(푹TV)자동,10900,0,일시불,<NA>,0,0,전표미매입,NaT,30118138

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   이용일         7 non-null      datetime64[ns]
 1   이용시간        7 non-null      string
 2   이용고객명       7 non-null      string
 3   이용카드명       7 non-null      string
 4   이용하신곳       7 non-null      string
 5   국내이용금액(원)   7 non-null      int64
 6   해외이용금액($)   7 non-null      int64
 7   결제방법        7 non-null      string
 8   가맹점정보       0 non-null      string
 9   할인금액        7 non-null      int64
 10  적립(예상)포인트리  7 non-null      int64
 11  상태          7 non-null      string
 12  결제예정일       2 non-null      datetime64[ns]
 13  승인번호        7 non-null      int64
dtypes: datetime64[ns](2), int64(5), string(7)
memory usage: 916.0 bytes

## 2. DB 데이터로 매핑

In [ ]:
# 국민카드 엑셀 데이터프레임을 가계부 지출 데이터프레임으로 매핑하는 함수
# sql/ddl/expenditure.sql 의 컬럼과 매핑됨

EXCHANGE_RATE_USD_TO_KRW = 1450
PAYMENT_TYPE = "card"
CARD_COMPANY = "kb"

def map_kb_card_df_to_expenditure(df: pd.DataFrame) -> pd.DataFrame:
    """국민카드 엑셀 데이터프레임을 가계부 지출 데이터프레임으로 매핑합니다."""
    mapped_df = pd.DataFrame()
    #사용일(Date)
    mapped_df["used_at"] = df["이용일"].dt.date

    #결제 수단 / 카드사(고정값 처리)
    mapped_df["payment_type"] = PAYMENT_TYPE
    mapped_df["payment_provider"] = CARD_COMPANY

    #사용처
    mapped_df["merchant_name"] = df["이용하신곳"].astype("string")

    #결제 방식
    mapped_df["installment_type"] = df["결제방법"].map(
        lambda x : "single" if x == "일시불" else "installment"
    )

    #금액 계산
     # 금액 계산 (국내 우선, 해외는 환율 적용)
    domestic = pd.to_numeric(
        df["국내이용금액(원)"],
        errors="coerce"
    ).fillna(0)

    foreign = pd.to_numeric(
        df["해외이용금액($)"],
        errors="coerce"
    ).fillna(0)

    mapped_df["amount"] = (
        domestic.where(domestic > 0, foreign * EXCHANGE_RATE_USD_TO_KRW)
        .round()
        .astype("int64")
    )

     # 할부 잔액
    mapped_df["remaining_amount"] = 0

    # 분류 (임시)
    mapped_df["category"] = "unknown"

    # 메모
    mapped_df["memo"] = None

    # 원본 식별자

    mapped_df["source_uid"] = (
        PAYMENT_TYPE
        + "_"
        + CARD_COMPANY
        + "_"
        + df["승인번호"].astype("string")
    )
    return mapped_df

In [43]:
expenditure_df = map_kb_card_df_to_expenditure(df)
expenditure_df.head()

,used_at,payment_type,card_company,merchant_name,installment_type,amount,remaining_amount,category,memo,source_uid
0,2026-01-03,card,kb,쿠팡(쿠페이),single,32600,0,unknown,None,card_kb_30118172
1,2026-01-03,card,kb,네이버페이,single,24840,0,unknown,None,card_kb_30118161
2,2026-01-03,card,kb,네이버페이,single,47500,0,unknown,None,card_kb_30118150
3,2026-01-03,card,kb,(주)딜리유통,single,42000,0,unknown,None,card_kb_30118141
4,2026-01-03,card,kb,웨이브(푹TV)자동,single,10900,0,unknown,None,card_kb_30118138

In [44]:
expenditure_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   used_at           7 non-null      object
 1   payment_type      7 non-null      object
 2   card_company      7 non-null      object
 3   merchant_name     7 non-null      string
 4   installment_type  7 non-null      object
 5   amount            7 non-null      int64
 6   remaining_amount  7 non-null      int64
 7   category          7 non-null      object
 8   memo              0 non-null      object
 9   source_uid        7 non-null      string
dtypes: int64(2), object(6), string(2)
memory usage: 692.0+ bytes

## 3. 지출 분류

In [45]:
# 지출 매핑 파일을 불러옵니다.
from pathlib import Path

def find_project_root(
    start_path: Path | None = None,
    markers=("pyproject.toml", ".git")
) -> Path:
    """
    start_path부터 상위 디렉토리를 탐색하며
    markers 중 하나가 존재하는 디렉토리를 프로젝트 루트로 반환
    """
    if start_path is None:
        start_path = Path.cwd()

    current = start_path.resolve()

    for parent in [current] + list(current.parents):
        if any((parent / marker).exists() for marker in markers):
            return parent

    raise RuntimeError("프로젝트 루트를 찾을 수 없습니다.")

PROJECT_ROOT = find_project_root(Path.cwd())

In [46]:
mapping_path = PROJECT_ROOT / "data" / "resources" / "expenditure_mapping.csv"
# mapping_path.exists()

mapping_df = pd.read_csv(mapping_path)
mapping_df = mapping_df.sort_values("priority").reset_index(drop=True)
mapping_df.head()

   priority match_type        pattern category     comment
0         1      exact  지에스수퍼 김포한강자이점       식비  GS수퍼 고정 지점
1         1   contains           GS수퍼       식비     GS수퍼 일반
2         1   contains          지에스25       식비    GS25 편의점
3         1   contains             씨유       편의      CU 편의점
4         1   contains           홈플러스       식비     홈플러스 계열

In [ ]:
import re

def map_category(merchant_name: str, mapping_df:pd.DataFrame) -> str | None:
    if pd.isna(merchant_name) or merchant_name == "":
        return None
    for _, row in mapping_df.iterrows():
        match_type = row["match_type"]
        pattern = row["pattern"]
        category = row["category"]
        if match_type == "exact":
            if merchant_name == pattern:
                return category
        elif match_type == "contains":
            if pattern in merchant_name:
                return category
        elif match_type == "regex":
            if re.search(pattern, merchant_name):
                return category
    return None

In [48]:
expenditure_df["category"] = expenditure_df["merchant_name"].apply(
    lambda x : map_category(x, mapping_df)
)
expenditure_df["category"] = expenditure_df["category"].fillna("미분류")

In [49]:
expenditure_df[["merchant_name", "category"]].head(20)

  merchant_name category
0       쿠팡(쿠페이)       쇼핑
1         네이버페이       쇼핑
2         네이버페이       쇼핑
3       (주)딜리유통       기타
4    웨이브(푹TV)자동       문화
5   NICE 결제대행_4       기타
6         구글플레이       문화

## 4. DB 저장

In [50]:
import sqlite3
db_path = PROJECT_ROOT / "data" / "db"/ "ledgerly.db"
conn = sqlite3.connect(db_path)

In [51]:
expenditure_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   used_at           7 non-null      object
 1   payment_type      7 non-null      object
 2   card_company      7 non-null      object
 3   merchant_name     7 non-null      string
 4   installment_type  7 non-null      object
 5   amount            7 non-null      int64
 6   remaining_amount  7 non-null      int64
 7   category          7 non-null      object
 8   memo              0 non-null      object
 9   source_uid        7 non-null      string
dtypes: int64(2), object(6), string(2)
memory usage: 692.0+ bytes

In [53]:
expenditure_df.to_sql(
    name="expenditure",
    con=conn,
    if_exists="append",
    index=False
)

7

In [56]:
fromdb_df =pd.read_sql("SELECT * FROM expenditure", conn)
fromdb_df

,id,used_at,payment_type,card_company,merchant_name,installment_type,amount,remaining_amount,category,memo,source_uid,created_at
0,1,2026-01-03,card,kb,쿠팡(쿠페이),single,32600,0,쇼핑,None,card_kb_30118172,2026-01-25 09:28:28
1,2,2026-01-03,card,kb,네이버페이,single,24840,0,쇼핑,None,card_kb_30118161,2026-01-25 09:28:28
2,3,2026-01-03,card,kb,네이버페이,single,47500,0,쇼핑,None,card_kb_30118150,2026-01-25 09:28:28
3,4,2026-01-03,card,kb,(주)딜리유통,single,42000,0,기타,None,card_kb_30118141,2026-01-25 09:28:28
4,5,2026-01-03,card,kb,웨이브(푹TV)자동,single,10900,0,문화,None,card_kb_30118138,2026-01-25 09:28:28
5,6,2026-01-01,card,kb,NICE 결제대행_4,single,110000,0,기타,None,card_kb_30118063,2026-01-25 09:28:28
6,7,2026-01-01,card,kb,구글플레이,single,19784,0,문화,None,card_kb_30118057,2026-01-25 09:28:28

In [57]:
fromdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                7 non-null      int64
 1   used_at           7 non-null      object
 2   payment_type      7 non-null      object
 3   card_company      7 non-null      object
 4   merchant_name     7 non-null      object
 5   installment_type  7 non-null      object
 6   amount            7 non-null      int64
 7   remaining_amount  7 non-null      int64
 8   category          7 non-null      object
 9   memo              0 non-null      object
 10  source_uid        7 non-null      object
 11  created_at        7 non-null      object
dtypes: int64(3), object(9)
memory usage: 804.0+ bytes